---

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
  - rubocop-rake

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false
